import { useEffect, useMemo, useState } from 'react';

const months = [
  ['JAN','Open','Reset after the holidays','open'],['FEB','Pensacola?','Sailing certification · 6–7 nights','idea'],['MAR','Couples?','Anniversary window begins','idea'],['APR','Anniversary','April 13 · late Mar/early Apr','idea'],['MAY','Tampa + Friends?','GST May 1–6 · Memorial Day?','busy'],['JUN','Quick reset','Asheville · Chattanooga','open'],['JUL','Summer option','Avon if points align','idea'],['AUG','Open','Protect breathing room','open'],['SEP','ISO + Friends?','Audit · Labor Day?','busy'],['OCT','Japan? / NC?','Fall Japan or family weekend','idea'],['NOV','Japan?','Fall alternative','idea'],['DEC','Cora birthday?','Ireland or Christmas tradition','idea']
];
const japan = [
  {name:'Mid-May',weather:'Mild, green and comfortable',crowds:'After Golden Week',year:'Close to Tampa; frees the fall',watch:'Start watching now'},
  {name:'October',weather:'Comfortable; some rain risk',crowds:'Moderate',year:'Good spacing after summer',watch:'Prime contender'},
  {name:'November',weather:'Cooler and often dry',crowds:'Foliage hot spots busier',year:'Compresses holidays',watch:'Best fall color chance'}
];
const destinations=['Japan','Québec City / Montréal','San Diego + Zoo','Ireland','Easy Caribbean resort','Pensacola','Nashville','Asheville','Avon','Chattanooga','Winston-Salem + Zoo','Athens','Amsterdam','Venice','Puerto Rico','Maine / Acadia'];
const buckets=['2027 priority','Watch for a deal','2028+','Not now'];
const initialPlans={japan:'',friends:'',sailing:'Undecided',nc:'Spring + Fall',cert1:'Unassigned',cert2:'Unassigned',tripMix:{international:true,friends:true,couples:true,nc:true,resets:true,birthday:false},destinations:Object.fromEntries(destinations.map((d,i)=>[d,i<6?'Watch for a deal':'2028+'])),deals:{Japan:'',Friends:'',Couples:''}};

function Choice({value,onChange,options}) { return <div className="choice-row">{options.map(o=><button key={o} className={value===o?'selected':''} onClick={()=>onChange(o)}>{o}</button>)}</div>; }
function Slide({kicker,title,children}) { return <section className="content-slide"><p className="eyebrow">{kicker}</p><h2>{title}</h2>{children}</section>; }

export default function MeetingView(){
  const [section,setSection]=useState(0);
  const [plan,setPlan]=useState(()=>{try{return {...initialPlans,...JSON.parse(localStorage.getItem('gardner2027meeting'))}}catch{return initialPlans}});
  useEffect(()=>localStorage.setItem('gardner2027meeting',JSON.stringify(plan)),[plan]);
  const set=(key,value)=>setPlan(p=>({...p,[key]:value}));
  const tripNights=useMemo(()=>Object.entries(plan.tripMix).reduce((n,[k,v])=>n+(v?({international:9,friends:5,couples:1,nc:4,resets:6,birthday:7}[k]||0):0),0),[plan.tripMix]);
  const toggleMix=k=>set('tripMix',{...plan.tripMix,[k]:!plan.tripMix[k]});
  const cycleDestination=d=>{const current=plan.destinations[d]||buckets[0];set('destinations',{...plan.destinations,[d]:buckets[(buckets.indexOf(current)+1)%buckets.length]})};
  const slides=[
    <section className="hero-slide" key="hero"><p className="eyebrow">THE GARDNER FAMILY · OCTOBER PLANNING MEETING</p><h1>What do we want<br/>2027 to <em>feel</em> like?</h1><p className="lead">Choose the anchors. Protect the breathing room. Be ready when the right deal appears.</p><div className="hero-stats"><div><strong>1</strong><span>Japan adventure</span></div><div><strong>1</strong><span>friends resort</span></div><div><strong>2</strong><span>NC weekends</span></div><div><strong>2</strong><span>companion certificates</span></div></div></section>,
    <Slide key="filter" kicker="01 · OUR FILTER" title="The trips that earn space"><div className="priority-grid">{[['01','Japan happens','The decision is when—not whether.'],['02','Keep it breathable','Short resets stay movable until anchors settle.'],['03','Travel with our people','Friends, family and one couples escape.'],['04','Use what we have','Put certificates and points to work.']].map(([n,t,c])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{c}</p></article>)}</div></Slide>,
    <Slide key="calendar" kicker="02 · BANDWIDTH MAP" title="See the whole year before filling it"><div className="month-grid">{months.map(([m,t,d,s])=><article className={s} key={m}><span>{m}</span><div><h3>{t}</h3><p>{d}</p></div></article>)}</div><p className="slide-note">May and September already carry work bandwidth. That matters even when the trip itself is fun.</p></Slide>,
    <Slide key="mix" kicker="03 · TRIP MIX" title="How much travel feels exciting—not exhausting?"><div className="mix-grid">{[['international','Major international','9 nights'],['friends','Easy friends resort','5 nights'],['couples','Anniversary escape','1 night'],['nc','Two NC weekends','4 nights'],['resets','Two quick resets','6 nights'],['birthday','Cora birthday / Christmas','6–8 nights']].map(([k,t,n])=><button className={plan.tripMix[k]?'selected':''} key={k} onClick={()=>toggleMix(k)}><span>{plan.tripMix[k]?'✓':'+'}</span><div><strong>{t}</strong><small>{n}</small></div></button>)}</div><div className="night-total"><strong>{tripNights}</strong><span>estimated personal travel nights · birthday trip calculated at 7</span></div></Slide>,
    <Slide key="japan" kicker="04 · THE ANCHOR" title="When does Japan fit best?"><div className="compare-grid">{japan.map(j=><button key={j.name} className={plan.japan===j.name?'selected':''} onClick={()=>set('japan',j.name)}><span className="select-dot">{plan.japan===j.name?'✓':''}</span><h3>{j.name}</h3><dl><dt>Weather</dt><dd>{j.weather}</dd><dt>Crowds</dt><dd>{j.crowds}</dd><dt>Effect on year</dt><dd>{j.year}</dd><dt>Deal posture</dt><dd>{j.watch}</dd></dl></button>)}</div><p className="prompt">Choose a target now. A backup can stay open until flights decide.</p></Slide>,
    <Slide key="friends" kicker="05 · FRIENDS TRIP" title="Which holiday weekend gets protected?"><div className="versus"><button className={plan.friends==='Memorial Day'?'selected':''} onClick={()=>set('friends','Memorial Day')}><small>MAY 29–31</small><h3>Memorial Day</h3><p>Close to Tampa, but farther from the September audit. Better separation from a fall Japan.</p></button><span>OR</span><button className={plan.friends==='Labor Day'?'selected':''} onClick={()=>set('friends','Labor Day')}><small>SEP 4–6</small><h3>Labor Day</h3><p>More planning runway, but shares a month with the ISO audit and could crowd fall Japan.</p></button></div><div className="mini-choice"><span>Trip style</span><strong>Easy resort · suites · little-kid friendly</strong></div></Slide>,
    <Slide key="resources" kicker="06 · USE WHAT WE HAVE" title="Give every certificate a job"><div className="resource-grid"><article><span>DELTA</span><h3>Companion certificate 01</h3><Choice value={plan.cert1} onChange={v=>set('cert1',v)} options={['Unassigned','Friends','Couples','Other']}/></article><article><span>DELTA</span><h3>Companion certificate 02</h3><Choice value={plan.cert2} onChange={v=>set('cert2',v)} options={['Unassigned','Friends','Couples','Other']}/></article><article><span>BONVOY / MVC</span><h3>Points opportunity</h3><p>Avon, Japan hotels, or a quick reset—book the exceptional redemption before it disappears.</p></article><article><span>DECISION</span><h3>Pensacola sailing</h3><Choice value={plan.sailing} onChange={v=>set('sailing',v)} options={['Undecided','Yes','No']}/></article></div></Slide>,
    <Slide key="draft" kicker="07 · DESTINATION DRAFT" title="Sort the ideas without overcommitting"><p className="instruction">Click a destination to move it to the next bucket.</p><div className="bucket-grid">{buckets.map(b=><div key={b}><h3>{b}</h3>{destinations.filter(d=>plan.destinations[d]===b).map(d=><button key={d} onClick={()=>cycleDestination(d)}>{d}<span>→</span></button>)}</div>)}</div></Slide>,
    <Slide key="family" kicker="08 · FAMILY WEEKENDS" title="Give the NC trips a purpose"><div className="family-options"><article><span>SPRING</span><h3>Winston-Salem + an event</h3><p>Earth Day, Greek Festival, or another Friday/Saturday family activity.</p></article><article><span>FALL</span><h3>Winston-Salem + Asheboro</h3><p>Boo at the NC Zoo, Apple Fest, the fair, or fall family time.</p></article></div><Choice value={plan.nc} onChange={v=>set('nc',v)} options={['Spring + Fall','Two fall weekends','Dates stay open']}/></Slide>,
    <Slide key="deals" kicker="09 · DEAL WATCH" title="Know what makes us book"><div className="deal-grid">{Object.keys(plan.deals).map(k=><label key={k}><span>{k}</span><input value={plan.deals[k]} onChange={e=>set('deals',{...plan.deals,[k]:e.target.value})} placeholder={k==='Japan'?'Example: under 100k miles RT':k==='Friends'?'Resort + flight ceiling':'Dates + fare threshold'}/></label>)}</div><p className="prompt">A deal is only useful if the dates, destination and total cost already fit the year.</p></Slide>,
    <Slide key="summary" kicker="10 · OUR 2027 PLAN" title="Leave with decisions, not just ideas"><div className="summary-grid"><article><span>JAPAN</span><strong>{plan.japan||'Still to choose'}</strong></article><article><span>FRIENDS</span><strong>{plan.friends||'Still to choose'}</strong></article><article><span>SAILING</span><strong>{plan.sailing}</strong></article><article><span>NC WEEKENDS</span><strong>{plan.nc}</strong></article><article><span>CERTIFICATE 01</span><strong>{plan.cert1}</strong></article><article><span>CERTIFICATE 02</span><strong>{plan.cert2}</strong></article></div><div className="next-actions"><h3>Before we close the laptop</h3><p>☐ Put protected windows on the calendar</p><p>☐ Set the first flight or points alerts</p><p>☐ Share the friends-trip weekend</p></div></Slide>
  ];
  return <div className="meeting-shell">{slides[section]}<footer className="slide-controls"><span>{String(section+1).padStart(2,'0')} / {String(slides.length).padStart(2,'0')}</span><div><button onClick={()=>setPlan(initialPlans)} className="reset">Reset</button><button disabled={!section} onClick={()=>setSection(s=>s-1)}>← Back</button><button disabled={section===slides.length-1} onClick={()=>setSection(s=>s+1)}>Next →</button></div></footer></div>;
}
