import { useEffect, useMemo, useState } from 'react';

const MONTHS=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const destinations=['Japan','Québec City / Montréal','San Diego + Zoo','Ireland','Easy Caribbean resort','Pensacola','Bay St. Louis · Logan + Ginny','Nashville','Asheville','Avon','Chattanooga','Winston-Salem + Zoo','Athens','Amsterdam','Venice','Puerto Rico','Maine / Acadia'];
const buckets=['2027 priority','Watch for a deal','2028+','Not now'];
const companionUses=['Unassigned','Tampa','Bay St. Louis','Colorado / Avon','Work trip','Friends resort','San Diego'];
const seedTrips=[
  {id:'tampa',title:'Tampa · GST',month:4,nights:5,type:'work',locked:true,status:'Confirmed',note:'May 1–6'},
  {id:'iso',title:'ISO audit',month:8,nights:0,type:'work',locked:true,status:'Confirmed',note:'September bandwidth'},
  {id:'pensacola',title:'Pensacola sailing',month:null,nights:7,type:'anchor',status:'Possible',note:'6–7 nights · February is an option, but timing is flexible'},
  {id:'anniversary',title:'Anniversary night',month:3,nights:1,type:'couples',status:'Targeted',note:'Anniversary April 13'},
  {id:'friends',title:'Friends resort',month:null,nights:5,type:'friends',status:'Flexible',note:'Group decision · availability + total cost'},
  {id:'japan',title:'Japan',month:null,nights:9,type:'anchor',status:'Priority',note:'Mid-May, October or November'},
  {id:'nc1',title:'NC family weekend 1',month:null,nights:2,type:'family',status:'Flexible',note:'Winston-Salem + purpose'},
  {id:'nc2',title:'NC family weekend 2',month:null,nights:2,type:'family',status:'Flexible',note:'Winston-Salem + purpose'},
  {id:'reset1',title:'Quick reset 1',month:null,nights:3,type:'reset',status:'Flexible',note:'Bay St. Louis, Asheville, Chattanooga or deal'},
  {id:'reset2',title:'Quick reset 2',month:null,nights:3,type:'reset',status:'Flexible',note:'Keep movable'},
  {id:'birthday',title:"Cora's birthday trip",month:null,nights:7,type:'birthday',status:'Optional',note:'6–8 nights · Christmas season'},
  {id:'michigan',title:'Michigan · Precise',month:null,nights:3,type:'work',status:'Possible',note:'Dates unknown'},
];
const japanOptions=[
  {name:'Mid-May',month:4,weather:'Mild, green and comfortable',crowds:'After Golden Week',effect:'Crowds May after Tampa; frees fall'},
  {name:'October',month:9,weather:'Comfortable; some rain risk',crowds:'Moderate',effect:'Good spacing after summer'},
  {name:'November',month:10,weather:'Cooler and often dry',crowds:'Foliage areas busier',effect:'Closer to birthday/Christmas travel'},
];
const initialPlan={version:2,japan:'',friends:'',sailing:'Undecided',nc:'Spring + Fall',cert1:'Unassigned',cert2:'Unassigned',destinations:Object.fromEntries(destinations.map((d,i)=>[d,i<7?'Watch for a deal':'2028+'])),deals:{Japan:'',Friends:'',Couples:''},calendar:seedTrips,scenario:''};

function Choice({value,onChange,options}){return <div className="choice-row">{options.map(o=><button key={o} className={value===o?'selected':''} onClick={()=>onChange(o)}>{o}</button>)}</div>}
function Slide({kicker,title,children,wide=false}){return <section className={`content-slide ${wide?'wide-slide':''}`}><p className="eyebrow">{kicker}</p><h2>{title}</h2>{children}</section>}
function levelFor(trips){const nights=trips.reduce((n,t)=>n+t.nights,0);const work=trips.filter(t=>t.type==='work').length;const score=nights+work*3;return score>=14?'Overloaded':score>=9?'Busy':score>=4?'Balanced':'Light'}

export default function MeetingView(){
  const [section,setSection]=useState(0); const [selected,setSelected]=useState(null); const [dragged,setDragged]=useState(null);
  const [plan,setPlan]=useState(()=>{try{const old=JSON.parse(localStorage.getItem('gardner2027meeting'));return {...initialPlan,...old,version:2,destinations:{...initialPlan.destinations,...old?.destinations},deals:{...initialPlan.deals,...old?.deals},calendar:old?.version===2&&old?.calendar?old.calendar:seedTrips}}catch{return initialPlan}});
  useEffect(()=>localStorage.setItem('gardner2027meeting',JSON.stringify(plan)),[plan]);
  const set=(key,value)=>setPlan(p=>({...p,[key]:value}));
  const updateTrip=(id,changes)=>set('calendar',plan.calendar.map(t=>t.id===id?{...t,...changes}:t));
  const moveTrip=(id,month)=>{const trip=plan.calendar.find(t=>t.id===id);if(!trip?.locked)updateTrip(id,{month});setDragged(null)};
  const selectJapan=o=>{setPlan(p=>({...p,japan:o.name,calendar:p.calendar.map(t=>t.id==='japan'?{...t,month:o.month}:t)}))};
  const selectFriends=(name,month)=>setPlan(p=>({...p,friends:name,calendar:p.calendar.map(t=>t.id==='friends'?{...t,month}:t)}));
  const cycleDestination=d=>{const current=plan.destinations[d]||buckets[0];set('destinations',{...plan.destinations,[d]:buckets[(buckets.indexOf(current)+1)%buckets.length]})};
  const applyScenario=name=>{const config=name==='Spring Japan'?{japan:4,friends:8}:{japan:10,friends:4};setPlan(p=>({...p,scenario:name,japan:name==='Spring Japan'?'Mid-May':'November',friends:name==='Spring Japan'?'Labor Day':'Memorial Day',calendar:p.calendar.map(t=>config[t.id]!==undefined?{...t,month:config[t.id]}:t)}))};
  const scheduled=useMemo(()=>plan.calendar.filter(t=>t.month!==null).sort((a,b)=>a.month-b.month),[plan.calendar]);
  const unscheduled=plan.calendar.filter(t=>t.month===null);
  const warnings=useMemo(()=>MONTHS.flatMap((m,i)=>{const ts=plan.calendar.filter(t=>t.month===i);const level=levelFor(ts);return level==='Overloaded'?[`${m} is overloaded (${ts.reduce((n,t)=>n+t.nights,0)} travel nights plus work bandwidth).`]:[]}),[plan.calendar]);
  const totalNights=plan.calendar.filter(t=>t.type!=='work'&&t.month!==null).reduce((n,t)=>n+t.nights,0);
  const calendarView=<div className="calendar-workshop">
    <div className="calendar-legend"><span><i className="work"/>Locked work</span><span><i className="anchor"/>Major trip</span><span><i className="family"/>Family / reset</span><strong>{totalNights} planned personal nights</strong></div>
    <div className="calendar-grid">{MONTHS.map((m,i)=>{const ts=plan.calendar.filter(t=>t.month===i);const level=levelFor(ts);return <div key={m} className={`calendar-month ${level.toLowerCase()}`} onDragOver={e=>e.preventDefault()} onDrop={()=>dragged&&moveTrip(dragged,i)}><header><b>{m}</b><span>{level}</span></header><div className="month-trips">{ts.map(t=><button draggable={!t.locked} onDragStart={()=>setDragged(t.id)} onClick={()=>setSelected(t.id)} className={`calendar-trip ${t.type}`} key={t.id}><strong>{t.title}</strong><small>{t.note}{t.locked?' · locked':''}</small></button>)}</div></div>})}</div>
    <div className="trip-tray" onDragOver={e=>e.preventDefault()} onDrop={()=>dragged&&moveTrip(dragged,null)}><header><div><b>Unscheduled tray</b><span>Keep possibilities here until they earn calendar space.</span></div><em>{unscheduled.length} open</em></header><div>{unscheduled.map(t=><button draggable onDragStart={()=>setDragged(t.id)} onClick={()=>setSelected(t.id)} className={`calendar-trip ${t.type}`} key={t.id}><strong>{t.title}</strong><small>{t.nights} nights · {t.status}</small></button>)}</div></div>
  </div>;
  const selectedTrip=plan.calendar.find(t=>t.id===selected);
  const slides=[
    <section className="hero-slide" key="hero"><p className="eyebrow">THE GARDNER FAMILY · OCTOBER PLANNING MEETING</p><h1>What do we want<br/>2027 to <em>feel</em> like?</h1><p className="lead">Choose the anchors. Create a steady rhythm of adventures to anticipate. Be ready when the right deal appears.</p><div className="hero-stats"><div><strong>1</strong><span>Japan adventure</span></div><div><strong>1</strong><span>friends resort</span></div><div><strong>2</strong><span>NC weekends</span></div><div><strong>2</strong><span>companion certificates</span></div></div></section>,
    <Slide key="filter" kicker="01 · OUR FILTER" title="The trips that earn space"><div className="priority-grid">{[['01','Japan happens','The decision is when—not whether.'],['02','Keep it breathable','Short resets stay movable until anchors settle.'],['03','Travel with our people','Friends, family and one couples escape.'],['04','Use what we have','Put certificates and points to work.']].map(([n,t,c])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{c}</p></article>)}</div></Slide>,
    <Slide key="mix" kicker="02 · TRIP MIX" title="How much travel feels exciting—not exhausting?"><div className="mix-grid">{[['Japan','9 nights'],['Friends resort','5 nights'],['Anniversary','1 night'],['Two NC weekends','4 nights'],['Two quick resets','6 nights'],["Cora's birthday",'6–8 nights']].map(([t,n])=><div className="mix-static" key={t}><span>✓</span><div><strong>{t}</strong><small>{n}</small></div></div>)}</div><div className="night-total"><strong>34–36</strong><span>possible personal travel nights before deciding what earns space</span></div></Slide>,
    <Slide wide key="calendar" kicker="03 · BUILD OUR YEAR" title="Create a year with something wonderful always on the horizon"><p className="instruction">Move trips into a rhythm that keeps us excited throughout the year. Drag between months, or click any card to edit it; only confirmed work anchors stay fixed.</p>{calendarView}</Slide>,
    <Slide key="scenario" kicker="04 · SCENARIO LAB" title="Two plausible shapes for the year"><div className="scenario-grid"><button className={plan.scenario==='Spring Japan'?'selected':''} onClick={()=>applyScenario('Spring Japan')}><small>SCENARIO A</small><h3>Spring Japan</h3><p>Japan in mid-May · offer Labor Day to friends</p><dl><dt>Strength</dt><dd>International anchor happens early</dd><dt>Tradeoff</dt><dd>May follows Tampa closely</dd><dt>Fall</dt><dd>More open after September</dd></dl></button><button className={plan.scenario==='Fall Japan'?'selected':''} onClick={()=>applyScenario('Fall Japan')}><small>SCENARIO B</small><h3>Fall Japan</h3><p>Offer Memorial Day to friends · Japan in November</p><dl><dt>Strength</dt><dd>More time to plan Japan</dd><dt>Tradeoff</dt><dd>Japan sits close to birthday travel</dd><dt>Fall</dt><dd>Heavier overall</dd></dl></button></div><p className="prompt">These are Gardner-family working scenarios. The friends trip stays tentative until all three couples compare availability and total cost.</p></Slide>,
    <Slide key="japan" kicker="05 · THE ANCHOR" title="When does Japan fit best?"><div className="compare-grid">{japanOptions.map(o=><button key={o.name} className={plan.japan===o.name?'selected':''} onClick={()=>selectJapan(o)}><span className="select-dot">{plan.japan===o.name?'✓':''}</span><h3>{o.name}</h3><dl><dt>Weather</dt><dd>{o.weather}</dd><dt>Crowds</dt><dd>{o.crowds}</dd><dt>Effect on year</dt><dd>{o.effect}</dd></dl></button>)}</div></Slide>,
    <Slide key="friends" kicker="06 · FRIENDS TRIP" title="Which weekend should we take to the group?"><div className="versus"><button className={plan.friends==='Memorial Day'?'selected':''} onClick={()=>selectFriends('Memorial Day',4)}><small>MAY 29–31 · CANDIDATE</small><h3>Memorial Day</h3><p>Close to Tampa, but farther from the September audit. Price it before polling the group.</p></button><span>OR</span><button className={plan.friends==='Labor Day'?'selected':''} onClick={()=>selectFriends('Labor Day',8)}><small>SEP 4–6 · CANDIDATE</small><h3>Labor Day</h3><p>More planning runway, but shares a month with the ISO audit. Price it before polling the group.</p></button></div><p className="prompt">Our selection is a preferred candidate—not a final decision. Confirm both other couples' availability, then compare the complete per-family cost.</p><div className="mini-choice"><span>Group requirements</span><strong>All 3 couples available · affordable total cost · easy resort · little-kid friendly</strong></div></Slide>,
    <Slide key="resources" kicker="07 · USE WHAT WE HAVE" title="Give every certificate a job"><div className="resource-grid"><article><span>DELTA</span><h3>Companion certificate 01</h3><Choice value={plan.cert1} onChange={v=>set('cert1',v)} options={companionUses}/></article><article><span>DELTA</span><h3>Companion certificate 02</h3><Choice value={plan.cert2} onChange={v=>set('cert2',v)} options={companionUses}/></article><article><span>CANDIDATE USES</span><h3>Where they may save the most</h3><p>Tampa, Bay St. Louis, Colorado/Avon, a qualifying work trip, the friends resort, or San Diego. A work trip only works if both travelers go and the fare is eligible.</p></article><article><span>BONVOY / MVC</span><h3>Points opportunity</h3><p>Avon, Japan hotels, or a quick reset—book an exceptional redemption before it disappears.</p></article><article><span>DECISION</span><h3>Pensacola sailing</h3><Choice value={plan.sailing} onChange={v=>set('sailing',v)} options={['Undecided','Yes','No']}/></article></div></Slide>,
    <Slide wide key="draft" kicker="08 · DESTINATION DRAFT" title="Sort the ideas without overcommitting"><p className="instruction">Click a destination to move it to the next bucket.</p><div className="bucket-grid">{buckets.map(b=><div key={b}><h3>{b}</h3>{destinations.filter(d=>plan.destinations[d]===b).map(d=><button key={d} onClick={()=>cycleDestination(d)}>{d}<span>→</span></button>)}</div>)}</div></Slide>,
    <Slide key="family" kicker="09 · FAMILY WEEKENDS" title="Give the NC trips a purpose"><div className="family-options"><article><span>SPRING</span><h3>Winston-Salem + an event</h3><p>Earth Day, Greek Festival, or another Friday/Saturday family activity.</p></article><article><span>FALL</span><h3>Winston-Salem + Asheboro</h3><p>Boo at the NC Zoo, Apple Fest, the fair, or fall family time.</p></article></div><Choice value={plan.nc} onChange={v=>set('nc',v)} options={['Spring + Fall','Two fall weekends','Dates stay open']}/></Slide>,
    <Slide key="deals" kicker="10 · DEAL WATCH" title="Know what makes us book"><div className="deal-grid">{Object.keys(plan.deals).map(k=><label key={k}><span>{k}</span><input value={plan.deals[k]} onChange={e=>set('deals',{...plan.deals,[k]:e.target.value})} placeholder={k==='Japan'?'Example: under 100k miles RT':k==='Friends'?'Resort + flight ceiling':'Dates + fare threshold'}/></label>)}</div><p className="prompt">A deal is useful only when the dates, destination and total cost already fit the year.</p></Slide>,
    <Slide wide key="summary" kicker="11 · OUR 2027 PLAN" title="Leave with decisions, not just ideas"><div className="final-plan"><div className="final-timeline">{scheduled.map(t=><article key={t.id}><span>{MONTHS[t.month]}</span><strong>{t.title}</strong><small>{t.nights?t.nights+' nights':t.note}</small></article>)}</div><aside><h3>Still unscheduled</h3>{unscheduled.map(t=><p key={t.id}>{t.title}</p>)}<h3>Decision check</h3><p>Japan: <b>{plan.japan||'Open'}</b></p><p>Friends candidate: <b>{plan.friends||'Open'}</b></p><p>Certificates: <b>{plan.cert1}, {plan.cert2}</b></p>{warnings.map(w=><p className="warning" key={w}>⚠ {w}</p>)}</aside></div><div className="next-actions"><h3>Before we close the laptop</h3><p>☐ Calendar the protected windows</p><p>☐ Set flight and points alerts</p><p>☐ Poll both couples with dates + cost</p></div></Slide>
  ];
  return <div className="meeting-shell">{slides[section]}<footer className="slide-controls"><span>{String(section+1).padStart(2,'0')} / {String(slides.length).padStart(2,'0')}</span><div><button onClick={()=>setPlan(initialPlan)} className="reset">Reset</button><button disabled={!section} onClick={()=>setSection(s=>s-1)}>← Back</button><button disabled={section===slides.length-1} onClick={()=>setSection(s=>s+1)}>Next →</button></div></footer>{selectedTrip&&<div className="decision-overlay" onClick={()=>setSelected(null)}><aside className="decision-drawer" onClick={e=>e.stopPropagation()}><button className="drawer-close" onClick={()=>setSelected(null)}>×</button><p className="eyebrow">TRIP DECISION</p><h2>{selectedTrip.title}</h2><label>Month<select value={selectedTrip.month??''} disabled={selectedTrip.locked} onChange={e=>moveTrip(selectedTrip.id,e.target.value===''?null:Number(e.target.value))}><option value="">Unscheduled</option>{MONTHS.map((m,i)=><option key={m} value={i}>{m}</option>)}</select></label><label>Nights<input type="number" min="0" value={selectedTrip.nights} disabled={selectedTrip.locked} onChange={e=>updateTrip(selectedTrip.id,{nights:Number(e.target.value)})}/></label><label>Status<select value={selectedTrip.status} disabled={selectedTrip.locked} onChange={e=>updateTrip(selectedTrip.id,{status:e.target.value})}>{['Confirmed','Priority','Targeted','Possible','Flexible','Optional'].map(x=><option key={x}>{x}</option>)}</select></label><label>Planning note<textarea value={selectedTrip.note} onChange={e=>updateTrip(selectedTrip.id,{note:e.target.value})}/></label>{selectedTrip.locked&&<p className="locked-note">This work commitment is locked in place.</p>}</aside></div>}</div>;
}
